# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: publish
on:
  workflow_call:
    inputs:
      NuGetDirectory:
        required: true
        type: string
    secrets:
      NUGET_APIKEY:
        required: true

defaults:
  run:
    shell: pwsh

jobs:
  create_nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3

    - run: dotnet pack --configuration Release --output ${{ inputs.NuGetDirectory }}

    - uses: actions/upload-artifact@v3
      with:
        name: nuget
        if-no-files-found: error
        retention-days: 7
        path: ${{ inputs.NuGetDirectory }}/*.nupkg

  validate_nuget:
    runs-on: ubuntu-latest
    needs: [ create_nuget ]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3

      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ inputs.NuGetDirectory }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ validate_nuget ]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: nuget
          path: ${{ inputs.NuGetDirectory }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3

      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ inputs.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }