# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: ASP.NET Docker CD

on:
  workflow_call:
    inputs:
      dockerAccount:
        required: true
        type: string
      applicationName:
        required: true
        type: string
      port:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no \
          ubuntu@168.75.82.21 ' \
          docker pull ${{ inputs.dockerAccount }}/${{ inputs.applicationName }}:main && \
          docker stop ${{ inputs.applicationName }} && \
          docker rm ${{ inputs.applicationName }} && \
          docker run -d --name ${{ inputs.applicationName }} -p ${{ inputs.port }}:8080 ${{ inputs.image }}:main'
