# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Python Docker CD

on:
  workflow_call:
    inputs:
      dockerAccount:
        required: true
        type: string
      applicationName:
        required: true
        type: string
      port:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH API
      uses: appleboy/ssh-action@master
      with:
        host: 152.67.63.173
        username: opc
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ inputs.dockerAccount }}/${{ inputs.applicationName }}:main && \
          docker stop ${{ inputs.applicationName }} && \
          docker rm ${{ inputs.applicationName }} && \
          docker run -d --name ${{ inputs.applicationName }} \
            --network default-network \
            -p ${{ inputs.port }}:8080 \
            -v /etc/app/config:/app/config \
            ${{ inputs.dockerAccount }}/${{ inputs.applicationName }}:main
            
